[functions.auth]
verify_jwt = false

[functions.media-upload]
verify_jwt = false

[functions.auth-sync]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.toggle-like]
verify_jwt = false

[functions.toggle-bookmark]
verify_jwt = false

[functions.toggle-follow]
verify_jwt = false

[functions.add-comment]
verify_jwt = false

[functions.delete-comment]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.create-post]
verify_jwt = false

[functions.create-story]
verify_jwt = false

[functions.update-post]
verify_jwt = false

[functions.delete-post]
verify_jwt = false

[functions.delete-story]
verify_jwt = false

[functions.update-avatar]
verify_jwt = false

[functions.toggle-block]
verify_jwt = false

[functions.create-conversation]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.send_notification]
verify_jwt = false
